---
abstract: 'File path utility'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Config: 0
  Devel::Hide: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Spec::Unix: 0
  File::pushd: 0
  List::Util: 0
  Test::Deep: 0
  Test::Fatal: 0
  Test::More: 0.96
  open: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Path-Tiny
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Path::Tiny:
    file: lib/Path/Tiny.pm
    version: 0.017
recommends:
  Unicode::UTF8: 0.58
requires:
  Carp: 0
  Cwd: 0
  Exporter: 5.57
  Fcntl: 0
  File::Copy: 0
  File::Path: 2.07
  File::Spec: 3.40
  File::Temp: 0.18
  File::stat: 0
  autodie::exception: 2.14
  constant: 0
  overload: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/path-tiny/issues
  homepage: https://metacpan.org/release/Path-Tiny
  repository: git://github.com/dagolden/path-tiny.git
version: 0.017
x_contributors:
  - 'Chris Williams <bingos@cpan.org>'
  - 'George Hartzell <hartzell@cpan.org>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Michael G. Schwern <mschwern@cpan.org>'
