use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.002005
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok('bin', 'lib');
__DATA__
BENCHMARKING
BinGOs
CRLF
Etheridge
Stringifying
canonpath
codepoints
cwd
dirname
lstat
mkpath
opena
openr
openrw
openw
realpath
subclasses
touchpath
unlinked
utf
David
Golden
lib
Path
Tiny
